name: Stop Azure TRE

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: The Github Actions environment to use
        type: environment
        default: CICD
        required: true
      DEVCONTAINER_TAG:
        description: Devcontainer tag to use
        type: string
        default: latest
        required: true

concurrency: "tre-stop-${{ github.ref }}"

jobs:
  stop_tre:
    name: Stop TRE
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Stop TRE
        uses: ./.github/actions/devcontainer_run_command
        with:
          COMMAND: "make tre-stop"
          DEVCONTAINER_TAG: ${{ inputs.DEVCONTAINER_TAG }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          CI_CACHE_ACR_NAME: ${{ secrets.ACR_NAME }}
          AZURE_ENVIRONMENT: ${{ vars.AZURE_ENVIRONMENT }}
          TRE_ID: ${{ secrets.TRE_ID }}
